### ISSUE TITLE
Air cancelled tier 3 attacks with scimitar

### ISSUE THREAD

**Issue by Jakeyyyyy** [punyhumangames/BladeSymphony#100]
Air cancelling a tier 3 attack with scimitar (jumping in the air as you perform a move you would do on the ground) doesn't do the tier 3 animation, but instead the tier 2 animation.

**Comment by Niklas-Eckhoff** [comment]
I cannot reproduce the bug. The image is a link to a YouTube video in which I show multiple Tier 3 Air Cancels with Scimitar Ryoku.

Could you be more specific? Perhaps you are referring to a specific character - move combination?

At the end of the video you can see that something went wrong (character jittering awkwardly). Not sure if it is relevant. Maybe a developer knows how to interpret this.

[![Scimitar Tier 3 Air Cancel](https://img.youtube.com/vi/b1wEU_7YZ3Q/0.jpg)](https://youtu.be/b1wEU_7YZ3Q)

**Comment by lkirbyPH** [comment]
We have been unable to reproduce this issue. If you have more information please let us know so that we can revisit it.
