### ISSUE TITLE
Duel Maps: Shurikens collide with players from different match in same arena

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#102]
The player who the shuriken collides with is not damaged by the shuriken. The shuriken curves upwards instead of literally "hitting" the player.

#86 is an FFA version of this bug. It has not been fixed at this point (01:37 on the 10th of November, 2018 (UTC)).

### Video of FFA version of this bug (click picture):
[![Shuriken collides with player out of duel in FFA](https://img.youtube.com/vi/o-yNQcMDnEI/0.jpg)](https://youtu.be/o-yNQcMDnEI)

**Comment by sampavlovic** [comment]
Should be fixed in the next patch

**Comment by Niklas-Eckhoff** [comment]
@samzanemesis 
@IkirbyPH
@urinal-cake

This bug is not fixed. Test your stuff before you declare it fixed, guys... and if you determine the cost of fixing isn't worth it, it would make sense to make a note...

### Video evidence, 2019-Feb-25 (click picture):
[![Shuriken collision 2](https://img.youtube.com/vi/-LxmOF10DS4/0.jpg)](https://youtu.be/-LxmOF10DS4)

I aim in the direction of another player. He is in the same arena but a different match.
