### ISSUE TITLE
FFA Outline not working

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#103]
**Requirements:**
Be on an **FFA server** with at least two other players _player P1_ and _player P2_. _Player P2_ should have a **static, known location** and should not be in a duel.

**Steps:**
(1) In **Settings -> Game**, make sure that **FFA Outline** and **Duel Outline** are set to **Enabled**.
(2) Start a duel with _player P1_.
(3) Face in the direction of _player P2_.

**Results:**
You do **not** see an **FFA outline** of _player P2_.

Note: I do not know what **Duel Outline** is supposed to do. Perhaps both of these settings or only one is broken. In the old game terms though, I would be referring to the **FFA Outline**.

Edit: slight change to match title; old version probably tested what is now referred to as "duel outline" while this now tests for "FFA outline". Just have a look at both settings because you know best what they're supposed to do, the problem is pretty obvious either way

**Comment by lkirbyPH** [comment]
We are tracking this bug internally. Our internal code for this bug is BS-222. Thanks for all your help!
