### ISSUE TITLE
Minor Bug: Missing texture on level up screen (judge, 2nd lvl)

### ISSUE THREAD

**Issue by xm88mx** [punyhumangames/BladeSymphony#106]
![20181115210726_1](https://user-images.githubusercontent.com/44852189/48584814-72987c80-e933-11e8-9e48-6249e093de1d.jpg)

**Comment by sampavlovic** [comment]
Should be fixed next patch, do you know which item you have received this level up?

**Comment by xm88mx** [comment]
I don't think you receive any item at level 2 because if you did it would show in the right side (if I remember correctly) and the only char that gets an item at level 2 is ryoku... Also this happens on level 3 too and at level 3 you get the standard helmet.

**Comment by lkirbyPH** [comment]
This issue seems to still be occurring but we are working on it! We are tracking it again with BS-286

**Comment by lkirbyPH** [comment]
should be fixed with the next patch.
