### ISSUE TITLE
Server Details shows "Max players" with level 1 as player list

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#107]
![max_players](https://user-images.githubusercontent.com/12057452/50367210-eeaf6100-057e-11e9-87c2-6cd316de3298.png)

Max players is not the name of a player on this server. Except for myself, only bots were on the server. Seems reproducible.

**Comment by lkirbyPH** [comment]
We are fixing this bug right now. Should be solved soon!

**Comment by lkirbyPH** [comment]
Should work with patch 5!
