### ISSUE TITLE
No new colors just copys

### ISSUE THREAD

**Issue by Crisis0** [punyhumangames/BladeSymphony#109]
Already mentioned to Urinal just posting it here to keep the overview.

![unknown 1](https://user-images.githubusercontent.com/40683658/50377940-1ce87b80-0627-11e9-950b-d1296db03522.png)

**Comment by Niklas-Eckhoff** [comment]
I kindly want to advice the developers to test their code after a change. Something like this would've been avoided with a quick look at the UI.

**Comment by lkirbyPH** [comment]
We are working on this bug now. Our internal tracking number for it is BS-257.

**Comment by urinal-cake** [comment]
@Niky1 This is not something we can easily test for, as it's not a 100% reproduction.
Until we have reproduction steps for this, we will not be able to fix it. Please provide your Steam ID or Steam Profile URL so that I can look into which items you should have.

**Comment by Niklas-Eckhoff** [comment]
@urinal-cake
Sorry for jumping to conclusions, my bad.

On that note though, how are items assigned? If they're assigned on level-up, that makes future adjustments pretty error-prone (imagine a user already having leveled up and you decide to add an item for a lower level). So if that's not already the case, it would probably be better to store leveled items (items unlocked through leveling) not for each user, but globally for each level and only store the level of each user.

And if a future feature requires the combination of level and user specific items, you could just have the level serve as a lock.

Steam ID: 76561198103749097
