### ISSUE TITLE
Level in customize menu and tab menu don't match

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#110]
See picture:

![level in customize menu and tab menu don t match](https://user-images.githubusercontent.com/12057452/50379590-dd815580-064d-11e9-9156-299156edcb69.jpg)

**Comment by lkirbyPH** [comment]
We are tracking this bug internally with tracking number BS-258

**Comment by Niklas-Eckhoff** [comment]
From looking at the picture again, I think it just cuts off the 5.

So it's likely just a UI bug!

**Comment by urinal-cake** [comment]
Yeah, we talked about this at standup today. It's just being cut off. It made it appear that levels were wrong for a few people. We'll resolve this, and then keep an eye on parity of levels between customization screen, summary screen and scoreboard.
