### ISSUE TITLE
Feature Request: Changing emblem intro

### ISSUE THREAD

**Issue by Crisis0** [punyhumangames/BladeSymphony#112]
The current Emblem intro is to fast and Looks a bit akward.
Make it 1 or 2 seconds longer Maybe with some Animation.
Change how it Looks:
My Suggestion is to take the look the summary screen offers, as intro with some  changes:

![20181223124847_1](https://user-images.githubusercontent.com/40683658/50385118-9b98f380-06cf-11e9-9428-a611accd6db3.jpg)

**Comment by Crisis0** [comment]
Name is ofc not optimal with ppl having way longer names than others.

**Comment by lkirbyPH** [comment]
We updated our emblem intros recently with more changes coming. Please let us know if you have more suggestions!
