### ISSUE TITLE
Request: remember certain customizations (e.g. colour) seperately for each char BS-341

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#114]
When you switch(*) to a character that does not have a certain colour and then back to the original char, the colour is lost. I think this is an undesirable effect.

Same happens for emblems.

(*) By "switch" I mean actually selecting the character, so you can play with it.

**Comment by urinal-cake** [comment]
Yeah, this is a bug.

**Comment by lkirbyPH** [comment]
Tracked with BS-341

**Comment by urinal-cake** [comment]
This was fixed in F2P Patch 1, I believe.
Tracked in Jira as BS-341 or at https://tracker.punyhuman.com/issues/5943
