### ISSUE TITLE
Training Mode: Classic mode not working

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#116]
Go into _Training Mode_ -> _AI Opponent_.
Whether you select _Classic Mode_ or _Arcade Mode_ as the _Fighting Style_ in the _Bot Setup Menu_, the duel will start in _Arcade Mode_.

Edit: Only happens sometimes. Working on a way to reproduce it. Idea is to wait for server change (in Training Mode). Then you start in Arcade Mode. Play a round there and switch to classic mode. You're still in Arcade Mode. Not sure if this procedure is always working.

**Comment by lkirbyPH** [comment]
Hey Niky. This should be fixed now! The issue was that the bot settings were respecting whatever settings you loaded them with the first time after loading the game, instead of reading whatever actual settings you wanted to play with. If this problem happens again, please let us know!
