### ISSUE TITLE
FFA unintentional switch to Arcade mode

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#118]
**Requirements:**
Be on FFA server with you and at least one other player P1.

**Testing procedure:**
(1) Go into Classic Mode & instruct player P1 to go into Arcade Mode
(2) **You** (!) request a duel with player P1 and s/he accepts.
(3) Finish the duel and wait to be completely out of it.

**Result:**
You are now in Arcade Mode.

**Comment by Niklas-Eckhoff** [comment]
It would be interesting to know if the converse is also true, i.e. if the same can be done for Classic Mode.

**Comment by lkirbyPH** [comment]
We are tracking this bug with tracking number: BS-271.
