### ISSUE TITLE
Bug: Purple Reflections

### ISSUE THREAD

**Issue by xm88mx** [punyhumangames/BladeSymphony#119]
On certain angles (mostly on ffa_district but I think it s not restricted to the map) hair and masks that contain hair reflect a missing texture purple. Might be a cubemap or baked lighting. I also couldn't get the effect on my own character.

(will add more pictures if I catch it, it s hard to screenshot it)

![20181227004303_1](https://user-images.githubusercontent.com/44852189/50478395-8545ad00-09d9-11e9-877c-ac92acb8799a.jpg)

**Comment by lkirbyPH** [comment]
Thanks for letting us know! We are now tracking this issue with tracking number BS-270.

**Comment by urinal-cake** [comment]
@xm88mx 
This issue should have been resolved with Patch 5. Closing as fixed.
