### ISSUE TITLE
Black patches on duel_temple (the void is seeping in)

### ISSUE THREAD

**Issue by MeoWHamsteR** [punyhumangames/BladeSymphony#12]
Black patches in appearing in duel_temple library arena.
Said by Josh to be a csm issue on Valve's side, but possible to work around.
They look like this:

https://cdn.discordapp.com/attachments/311559971273834496/462345047656890378/unknown.png

**Comment by misyltoad** [comment]
unrelated to void/leaks.

**Comment by misyltoad** [comment]
This was worked around by disabling CSM on this map.
