### ISSUE TITLE
Bug: Linux - Windows different UI BS-269

### ISSUE THREAD

**Issue by xm88mx** [punyhumangames/BladeSymphony#121]
Linux:

![20181230160255_1](https://user-images.githubusercontent.com/44852189/50595701-2afd8e00-0eaa-11e9-85df-262acc9cdff8.jpg)

Windows:

![20181231203351_1](https://user-images.githubusercontent.com/44852189/50595709-3781e680-0eaa-11e9-9bf2-2b33f14ba5b7.jpg)

The major difference is the stance image, on linux there are some seemingly random letters (different letters for each stance and for each character) while windows has actual images. Also, fonts differ slightly, linux it's a little bigger than on windows.

**Comment by lkirbyPH** [comment]
This issue has been around for a while but we haven't had a chance to fix it yet. Some of the fonts for linux (and mac too) aren't being read properly, but we are working on getting it sorted out! Just added tracking number BS-269 for the issue.

**Comment by urinal-cake** [comment]
Hey @xm88mx has this been fixed yet? We're tracking it here now:
https://tracker.punyhuman.com/issues/6015

**Comment by urinal-cake** [comment]
As of March 1st, this still occurs on Mac. Closing here and will continue to track on Redmine
