### ISSUE TITLE
Crash while map change BS-282

### ISSUE THREAD

**Issue by Crisis0** [punyhumangames/BladeSymphony#122]
It happens once in a while that my game crashes back to Desktop after a regular map Change.

**Comment by lkirbyPH** [comment]
Thanks for letting us know Crisis. We are tracking your issue with BS-282. Hopefully we can get it all sorted out for you!

**Comment by urinal-cake** [comment]
@Crisis0 
This should be fixed with the F2P release. Please let us know if you see different results or if this starts happening again.
