### ISSUE TITLE
Overlaying texts, missing texture and item misplaced

### ISSUE THREAD

**Issue by PaperJack315** [punyhumangames/BladeSymphony#125]
The name of this issue is selfexplainatory.
![20190116173638_1](https://user-images.githubusercontent.com/28924911/51282165-b287e880-19e4-11e9-90a3-821f800e6223.jpg)
![20190116172008_1](https://user-images.githubusercontent.com/28924911/51282167-b287e880-19e4-11e9-9c1c-656dabaf6161.jpg)

**Comment by lkirbyPH** [comment]
Hey there PaperJack! This should be fixed now. Let us know if you experience it again!
