### ISSUE TITLE
(Bug) Testing branch: Getting shuried while in air makes camera lag behind

### ISSUE THREAD

**Issue by xm88mx** [punyhumangames/BladeSymphony#127]
If you get shuried while in air you get knocked down if you continue to press space you will get up and start jumping but the camera will lag behind your character. (as if the lag slider in the camera settings is turned to max) If you stop jumping and wait a sec everything goes back to normal.

Note this is on the testing brach.

**Comment by xm88mx** [comment]
This bug went live with patch 5.

**Comment by lkirbyPH** [comment]
This is now being tracked as BS-317! Thanks for letting us know about it!

**Comment by urinal-cake** [comment]
According to @xm88mx this no longer happens. Closing.
