### ISSUE TITLE
(Bug) Testing branch: elevator doors missing textures BS-334

### ISSUE THREAD

**Issue by xm88mx** [punyhumangames/BladeSymphony#128]
![20190121232146_1](https://user-images.githubusercontent.com/44852189/51499677-db88ee80-1dd3-11e9-82a6-932bd15ac4af.jpg)

![20190121232143_1](https://user-images.githubusercontent.com/44852189/51499683-e2affc80-1dd3-11e9-9808-bf44831ef5ab.jpg)

Note this is only on the testing branch on live they are ok

**Comment by lkirbyPH** [comment]
we are tracking this as BS-334

**Comment by lkirbyPH** [comment]
will be fixed next patch
