### ISSUE TITLE
Voice chat icon does not show up when using push to talk BS-303

### ISSUE THREAD

**Issue by Narny94** [punyhumangames/BladeSymphony#130]

**Comment by lkirbyPH** [comment]
Hey Narny, This bug is getting tracked on JIRA as BS-303. Thanks for letting us know!

**Comment by urinal-cake** [comment]
@Narny94 
This should be fixed in the F2P release. You should see an icon above a player's head when they are voice chatting, as well as on the game's UI. Please let us know if you see different results, or if this starts happening again.

**Comment by Narny94** [comment]
There is no icon above players head's I think. And when I hold down push to talk people see it in the UI however I can't see it myself.

**Comment by urinal-cake** [comment]
This has been addressed in Build Jenkins #1404 Src: ea1cbeff-2021-11-15 Game: a267452e-2021-11-10 which is currently latest on the release_candidate branch of Blade Symphony.

**Comment by urinal-cake** [comment]
![image](https://user-images.githubusercontent.com/7855304/161267522-a097ae58-929c-45ab-a897-f0a48690575f.png)
