### ISSUE TITLE
When both players are alive after the last round, they can attack eachother BS-337

### ISSUE THREAD

**Issue by WindmillWonder** [punyhumangames/BladeSymphony#132]
Doesn't occur in a round that doesnt end the match.
At first after the round attacks are disabled, but probably when the summary screen would show up, it is possible to attack again

**Comment by lkirbyPH** [comment]
We are tracking this bug as BS-337. Thanks for letting us know about it!

**Comment by urinal-cake** [comment]
Fixed with the latest F2P release. Please let us know if this still happens or starts happening again.
