### ISSUE TITLE
White screen bug before level up screen BS-335

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#133]
Sometimes this happens before the level up screen shows. Press the **ESC keyboard button** to go to the level up screen from where you can continue the game as usual. I have personally only seen this happen on FFA servers.
![white screen bug](https://user-images.githubusercontent.com/12057452/52524668-e4b4ff00-2c9f-11e9-86fc-e15a5b3c15d9.jpg)

**Comment by lkirbyPH** [comment]
Tracking this as BS-335! Thanks for letting us know.

**Comment by lkirbyPH** [comment]
will be fixed next patch
