### ISSUE TITLE
won't load on Ubuntu now BS-331

### ISSUE THREAD

**Issue by LiamDawe** [punyhumangames/BladeSymphony#134]
As of the latest update, it no longer loads on Linux.

Log: https://pastebin.com/Nn6tSq23
DMP file: http://www.filedropper.com/crash201902151209521

(Also posted in Discord)

**Comment by urinal-cake** [comment]
Hey @LiamDawe 
Can you just confirm that this is in fact fixed? I'm aware you sent some other crashes, potentially related to texture streaming, but I wanted to see if the game will at least run on Ubuntu now.

**Comment by LiamDawe** [comment]
It did work for a time, but it seems I get a crash before the menu once again now.

DMP file: http://www.filedropper.com/crash201902211349411

**Comment by urinal-cake** [comment]
Hi @LiamDawe 
We put in a fix for this in the latest F2P release. Are you still seeing this issue?

**Comment by LiamDawe** [comment]
Nope, okay now.
