### ISSUE TITLE
Cursor doesn't show up on game (BS-242)

### ISSUE THREAD

**Issue by DogeInTheUniverse** [punyhumangames/BladeSymphony#139]
Sometimes the cursor doesn't show up on my game, so I had to click my cursor on a random button

**Comment by lkirbyPH** [comment]
We are working on this issue right now. being tracked as BS-242

**Comment by urinal-cake** [comment]
Hey @DogeInTheUniverse This issue should have been sorted in F2P Patch 2, can you check to see if it still happens?

**Comment by urinal-cake** [comment]
We haven't yet heard from @DogeInTheUniverse since F2P Patch 2 came out, so this is being closed and will continue to be tracked on our Redmine: https://tracker.punyhuman.com/issues/6040
