### ISSUE TITLE
Time-out "One-dot" loading screen

### ISSUE THREAD

**Issue by shadowhunter1423** [punyhumangames/BladeSymphony#26]
So whenever I try to connect to a server I get a loading screen with only one dot, after a while I time out.

--System Information--

Laptop
GPU: Nvidia GTX 1050 4gb     Driver version: 398.36
CPU: Intel core i5-7300hq @2.50 GHz
RAM: 8gb
OS: Windows 10 Home x64   Version: 1803   Build: 17134.137 (17134.165 now, issue still persists)

--Log--

Connecting to public(95.179.166.161:27017) ...
[NET] Sending simple small packageServer using '<none>' lobbies, requiring pw no, lobby id ffffffffffffffff
[NET] Client connect packet too large for 95.179.166.161:27017, total size 1060 bytes ( 20 header, 770 info, 14 cookie, 256 auth )
[NET] Sending simple small packageConnected to 95.179.166.161:27017
Disconnect: lavamen1331 timed out.
Disconnect: lavamen1331 timed out.

**Comment by misyltoad** [comment]
Fixed
