### ISSUE TITLE
The game doesn't close. BS-149

### ISSUE THREAD

**Issue by case-andrson** [punyhumangames/BladeSymphony#33]
When I close the game, the process berimbau.exe continues to work.
![2018 07 26-08 52](https://user-images.githubusercontent.com/41531161/43241076-03f0b28a-90b3-11e8-82cf-23ef87c6f6a2.png)
![2018 07 26-08 54](https://user-images.githubusercontent.com/41531161/43241086-0bdfd250-90b3-11e8-8a11-602c14897ff9.png)

**Comment by lkirbyPH** [comment]
We are tracking this issue on Jira! Our internal tracking number for this bug is BS-149. We are having a hard time finding steps to reproduce this bug. Are you still experiencing the problem, or do you have any more information about how you got it to happen?

**Comment by sampavlovic** [comment]
Should be fixed in the next update
