### ISSUE TITLE
Pressing escape does not fully close out the Video options

### ISSUE THREAD

**Issue by GlamazonianRage** [punyhumangames/BladeSymphony#37]
Pressing escape does not fully close out the Video options

Repro:
- Press Esc
- Click any setting option
- Press Esc
- Press Esc again
- Note that the menu did not close out completely, and all Apply/Done/Reset/Back/Default options are gone

![image](https://user-images.githubusercontent.com/42359810/44062384-15db6802-9f2a-11e8-9226-3879f200b050.png)

**Comment by misyltoad** [comment]
This was fixed with the server browser fix for this.
