### ISSUE TITLE
 Debug text appears on the "Use Defaults" options

### ISSUE THREAD

**Issue by GlamazonianRage** [punyhumangames/BladeSymphony#38]
![image](https://user-images.githubusercontent.com/42359810/44061927-524c88ae-9f28-11e8-8dd7-db29d2e69d8e.png)

![image](https://user-images.githubusercontent.com/42359810/44061948-714b8c5a-9f28-11e8-8353-e5bfd9fb8ae5.png)

Debug text appears on the "Use Defaults" options

- Press Esc
- Change any setting option
- Click Use Defaults

**Comment by lkirbyPH** [comment]
This should be fixed by next patch!
