### ISSUE TITLE
Weapon and String Counter/Tactical Mode issues in Tutorial

### ISSUE THREAD

**Issue by Drejzer** [punyhumangames/BladeSymphony#4]
During the tutorial the game informs that Tactical Mode enables String counter and sword types, assumes that tactical mode is active, and then asks the player to perform "heavy string 3"
![image](https://user-images.githubusercontent.com/14893831/42092636-d9c14c4a-7ba9-11e8-8ca3-4060193b23a4.png)
but neither shows how to enable the Tactical Mode, nor what it does, nor activates it for the duration of the tutorial
(nota bene: the tip should read "You can *switch* stances mid-combo")

Later on the tutorial explains sword types, and asks to execute their combos or use their defensive abilities, while the player is locked to the Longsword (though. it does swap models):
![image](https://user-images.githubusercontent.com/14893831/42093488-ca74ce12-7bac-11e8-8cb1-3de3c8f0d58b.png)

And "Swich to Tactical Mode" doesn't work (at least i the tutorial).

**Comment by Crisis0** [comment]
Sry I borrowed your pics to make a summarize of the Tutorial issue :)

**Comment by misyltoad** [comment]
Duplicate.
