### ISSUE TITLE
The "Cancel" button does not function in the "Use Defaults" menu

### ISSUE THREAD

**Issue by GlamazonianRage** [punyhumangames/BladeSymphony#40]
The "Cancel" button does not function in the "Use Defaults" menu

- Load into Blade Symphony (main menu or in game)
- Press Esc
- Change any setting
- Click "Use Defaults"
- Attempt to click "Cancel"

![image](https://user-images.githubusercontent.com/42359810/44062939-78fa23d6-9f2c-11e8-9f41-ba822f09ca82.png)

**Comment by lkirbyPH** [comment]
This should be fixed in the next patch!
