### ISSUE TITLE
Training Mode: Setting bot weapon not working

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#41]
Operating system: Windows x64
Blade Symphony version: Windows x64

**Comment by Vivianite** [comment]
Upon first boot, it also overrides the style selection to always be arcade on the first duel if classic was set.  however, when switched back to arcade mode the second duel is now set in classic instead.  character selection and behavior seemed to be unaffected.

**Comment by sampavlovic** [comment]
Fixed in the next update

**Comment by Niklas-Eckhoff** [comment]
Tested, fixed
