### ISSUE TITLE
Bug: Changing display mode in the settings causes Field of View to reset BS-232

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#44]

**Comment by lkirbyPH** [comment]
Thank you for bringing this bug to our attention! Our internal tracking number for this bug is BS-232.

**Comment by Niklas-Eckhoff** [comment]
**Testing procedure:**
(1) join game server
(2) ESC -> Video -> set "Display Mode" to "Windowed (No Border)" -> Apply
(3) Game -> Camera Options -> adjust Field Of View to maximum value -> Done -> Done -> Back

(4) Observe current Field of View
(5) ESC -> Video -> set "Display Mode" to "Full Screen" -> Apply -> Back
(6) Notice FoV has changed
