### ISSUE TITLE
Rapier: Guard mechanism not working

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#47]

**Comment by Vivianite** [comment]
Tested and working as intended in classic style.

**Comment by Niklas-Eckhoff** [comment]
True, I just tested it again. It's just so bad that it barely works, especially if your opponent is a bit closer. Since this is a balancing issue and not a bug, I am closing this thread.

**Comment by Niklas-Eckhoff** [comment]
Turns out it was indeed a bug, but fixed now anyway.
