### ISSUE TITLE
duel_castle lighting issue

### ISSUE THREAD

**Issue by CAMaera** [punyhumangames/BladeSymphony#5]
duel_castle rapidly flickers between bright and dark, incredibly hard on the eyes. Here are two still screenshots of what the dark and light states it flickers between look like. 

![20180629164546_1](https://user-images.githubusercontent.com/40705119/42117890-ab5f08ac-7bbc-11e8-8ce4-92ac95d5a338.jpg)
![20180629164548_1](https://user-images.githubusercontent.com/40705119/42117893-af956948-7bbc-11e8-8677-03bdb6d913b1.jpg)

**Comment by misyltoad** [comment]
This level hasn't been recompiled yet. I assume a recompile will fix it. I'm not even sure we have the VMF for this though.
