### ISSUE TITLE
Players cannot join a server through the server details panel

### ISSUE THREAD

**Issue by GlamazonianRage** [punyhumangames/BladeSymphony#52]
Clicking "Connect" sends the player back to the server list instead of the server.

Repro:
1. Load up Blade Symphony Beta
2. Click Play Online
3. Click Browse
4. Click any server
5. Click Details
6. Click Connect

**Comment by lkirbyPH** [comment]
We are tracking this issue on Jira! Our internal tracking number for this bug is BS-156.
