### ISSUE TITLE
Brightness setting disappears in Windowed mode 

### ISSUE THREAD

**Issue by GlamazonianRage** [punyhumangames/BladeSymphony#56]
![image](https://user-images.githubusercontent.com/42359810/44748717-67754380-aade-11e8-829f-e4df6ec60c2b.png)
![windowed](https://user-images.githubusercontent.com/42359810/44748988-4103d800-aadf-11e8-892d-b9cd335aa82f.png)

Brightness setting disappears in Windowed mode 
Repro:
1.  Load into Blade Symphony beta in full screen
2.  Open the video settings
3.  Note the brightness settings
4.  Switch to windowed
5.  Open the video settings
6.  Note that its goneeee!

**Comment by misyltoad** [comment]
This is intentional, its not possible to change brightness due to the way we change monitor gamma stuff in fullscreen.
