### ISSUE TITLE
duel_winter boundaries and waterfall crash

### ISSUE THREAD

**Issue by CAMaera** [punyhumangames/BladeSymphony#6]
Simply put, duel_winter has no boundaries on any of its arenas. You can simply walk out to the edge of the world, but if a player tries to enter waterfall(through joining it or walking out of bounds to it) the game will crash. 

![walk out](https://user-images.githubusercontent.com/40705119/42118096-e7a769ca-7bbd-11e8-8124-a00d7de78f2d.PNG)

**Comment by Crisis0** [comment]
Made a Video for it : https://youtu.be/yaDrqQgmXL8

**Comment by Agameofscones** [comment]
This should be fixed by the end of the day PST. It appears I forgot to enable some visgroups while compiling.

**Comment by urinal-cake** [comment]
The issue of lack of player clips should be fixed, I'm uncertain of the death water issue, however. Can you please test this?
