### ISSUE TITLE
Unknown FPS drop after prologed play on a specific server

### ISSUE THREAD

**Issue by Vivianite** [punyhumangames/BladeSymphony#60]
Numerous players (5~10) during the play-test on Tuesday Aug. 28 were experiencing performance degradation, eventually leading to extreme server instability to the point of crashing the server.

This adversely affects the client's stability, leading to a "hang" similarly mentioned in #53 , requiring a task manager close or a windows error reporting close. this does not properly generate a *.mdmp  or an option to submit a crash report as requested.  to some players, even attempting to submit a crash report has resulted in the following: 
![image](https://user-images.githubusercontent.com/42749463/44752767-a5279b80-aae1-11e8-8560-fdc1768706f6.png)

**Comment by sampavlovic** [comment]
Should be much mitigated if not completely fixed, please send us a crashdump if this happens again
