### ISSUE TITLE
Missing textures on the walls and floor in the demo

### ISSUE THREAD

**Issue by adih2001** [punyhumangames/BladeSymphony#61]
I've noticed that there are missing textures on the walls and floor in the demo.
Here is a screenshot:
![20180830210540_1](https://user-images.githubusercontent.com/25685432/44871288-09418f80-ac9b-11e8-883d-2d0ec0e7a2ef.jpg)
To reproduce this, you just have to open the tutorial and you will notice it.

**Comment by Vivianite** [comment]
Tested this and can confirm it's a issue, one of the reflective maps are missing a valid texture.
however, this is a issue with Patrice_Box as a map and is not exclusive to the tutorial.

**Comment by misyltoad** [comment]
These are cubemaps, and this will be fixed when practice box gets recompiled
