### ISSUE TITLE
duel_district invisible building

### ISSUE THREAD

**Issue by CAMaera** [punyhumangames/BladeSymphony#7]
This building in Alley has no wall.

![invisiblebuilding](https://user-images.githubusercontent.com/40705119/42118142-4543b7fa-7bbe-11e8-915c-fa08a77892c1.PNG)

**Comment by CAMaera** [comment]
Worth noting that the pipes in this area also cull out at a very short range as per my other post on free_district.

**Comment by urinal-cake** [comment]
This should be fixed on the latest build on Steam, can you please test?

**Comment by CAMaera** [comment]
Not fixed as of latest update.
