### ISSUE TITLE
Ryoku pony tail

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#70]
Switch to Pure or Vanguard, then to Ryoku (don't actually select the character) and in the menu, Ryoku will appear to have a ponytail.

![20180907232545_1](https://user-images.githubusercontent.com/12057452/45243997-35da5480-b2f6-11e8-8281-4cbc4daa6a48.jpg)

**Comment by misyltoad** [comment]
Cute! I think it suits him.

When you say "Don't actually select the character" what do you mean?
Can you give step by step instructions

**Comment by Niklas-Eckhoff** [comment]
@Joshua-Ashton I cannot reproduce the issue anymore, this seems to be _fixed_. The original procedure was to:

(1) Go to the **customize menu**
(2) LM click the **Ryoku thumbnail**
(3) LM click the **Select button**
(4) LM click the **Pure thumbnail** or LM click the **Vanguard thumbnail**
(5) LM click the **Ryoku thumbnail**

Could you have a look at issue #87? I think this one is the most noticeable and annoying out of all the bugs that are in the game right now.

**Comment by misyltoad** [comment]
Closing this then, and will do!
