### ISSUE TITLE
FFA: Can see corpse from another duel

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#82]
**Requirements:**
Be on an FFA server with four test participants (you, _your opponent_, _player P1_, _player P2_). Throghout the test-procedure, all four test participants remain in close proximity to each other.

**Steps:**
(1) Direct _player P1_ and _player P2_ to start a duel with each other and then wait.
(2) You start a duel with _your opponent_.
(3) Direct _player P1_ to kill _player P2_. Tell _player P2_ to notify you via chat when his character dies.
(4) Wait until the notification from _player P2_.

**Results:**
Look around and you will be able to see a corpse pop up which disappears shortly after.

Probably related to #92.

**Comment by Niky1** [comment]
I fucked up. Closed, same as #92.

**Comment by Niklas-Eckhoff** [comment]
#92 and this one are not the same, albeit very similar. This one is in FFA, while the other is on duel servers.

I assume the whole FFA map is being handled as an arena internally when two players are dueling each other in FFA. So solving one will likely fix the other, but not necessarily (which is why I reopened this issue).

**Comment by lkirbyPH** [comment]
We are tracking this issue on Jira! Our internal tracking number for this bug is BS-157.
