### ISSUE TITLE
If you join a queue with 1 player already queuing, you will skip this player

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#87]
**Requirements:**
Be on a dueling server with an arena with a _match M_ that has exactly 2 players dueling each other and exactly 1 _player P_ in its queue. To the losing player of the most recent duel we refer to as _player L_. After step (1) no player must leave or join the queue, including leaving and then rejoining.

**Steps:**
(1) Join _match M_
(2) Wait until it is your turn dueling
(3) Complete the duel

Optional:
(4) Watch the duel being completed or complete the duel.
(5) Watch the duel being completed or complete the duel.
.
.
.
(last) end

**Results:**
Notice that you do not need to wait for _player P_ to duel before it is your turn (you will skip them). _Player L_ will appear in front of _player P_. For every step after (2) this continues to hold true.

This might be related to #81, but it is not the same. I am not even sure if #81 still happens, but this certainly does.

**Comment by Niklas-Eckhoff** [comment]
It would be interesting to know if this also happens when 2 players are dueling and 3 players are queuing and then 1 player leaves.

**Comment by misyltoad** [comment]
@Niky1 Can you retest this on the releasecandidate branch? Thanks!

**Comment by urinal-cake** [comment]
It's not necessary to test this on the release candidate branch. The latest public build, as of 11/5, has the latest code.

**Comment by Niklas-Eckhoff** [comment]
@Joshua-Ashton, @urinal-cake
I can't gather anyone to test this issue with me, sorry. I will report when I see it happening again or can somehow get enough players to test it in the future.

**Comment by urinal-cake** [comment]
This has not been fixed in Patch 4, like we thought.

**Comment by Niklas-Eckhoff** [comment]
Great, this is finally fixed!
