### ISSUE TITLE
Sometimes you have to create a new match to join an already existing one

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#89]
This is possibly at the start of the map.
Maybe switching to the arena first (viewing it) and then joining might work.

Either way, I wanted to write this down. Unfortunately right now I cannot find when exactly it happens because lack of players.

**Comment by lkirbyPH** [comment]
We are tracking this issue on Jira! Our internal tracking number for this bug is BS-159.
