### ISSUE TITLE
Server details -> connect doesn't actually connect you

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#90]
**Requirements:**
Be in the _Server Browser game menu_.

**Steps:**
(1) LM click on a server
(2) LM click on the _Details UI element_
(3) LM click on the _Connect UI element_

**Results:**
You are back in the _Server Browser game menu_ and have not connected to the server.

You can now of course connect to the server but this isn't the purpose of the UI element.

**Comment by sampavlovic** [comment]
Duplicate of #52
