### ISSUE TITLE
Minor Bug: Resetting keybinds UI

### ISSUE THREAD

**Issue by xm88mx** [punyhumangames/BladeSymphony#99]
The title for the reset keybinds to default says #Portal2_keyboardsettingconf and the accept button says #Portal2_buttonaction_reset.

![20181108001254_1](https://user-images.githubusercontent.com/44852189/48167378-355d3a80-e2f4-11e8-8539-9e482bcd0b32.jpg)

**Comment by lkirbyPH** [comment]
Jira BS-172

**Comment by lkirbyPH** [comment]
Occurs from the key bind page in game not from the main menu.

**Comment by lkirbyPH** [comment]
This bug led us to a couple of other text box errors that we are working on now. Our internal tracking number for this bug is BS-172. Thanks for all your help!
